# Generated by Django 3.2 on 2021-04-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='category',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
